### ISSUE TITLE
aws_http_tokens_state in readme of doc should be ec2_metadata_http_tokens

### ISSUE THREAD

**Issue by xueli181114** [terraform-redhat/terraform-provider-rhcs#105]
According to code:
       ` Ec2MetadataHttpTokens     types.String `tfsdk:"ec2_metadata_http_tokens"``
The defined variable should be `ec2_metadata_http_tokens`
But it shows `aws_http_tokens_state` in below readme
https://github.com/terraform-redhat/terraform-provider-ocm/blob/9c256686a8b7e3e6615fbbe040834cfa4d210374/docs/resources/cluster_rosa_classic.md

**Comment by nirarg** [comment]
Hi @xueli181114 ,
That was fixed in 1.1.0, please verify

Thanks,
Nir
