### ISSUE TITLE
Documentation Inconsistencies

### ISSUE THREAD

**Issue by OurFriendIrony** [terraform-redhat/terraform-provider-rhcs#179]
The documentation for provider version [1.0.5](https://registry.terraform.io/providers/terraform-redhat/ocm/1.0.5/docs/resources/cluster_rosa_classic) has a discrepancy between the name of the resources.  

![image](https://github.com/terraform-redhat/terraform-provider-rhcs/assets/8308534/14335828-8e2b-4e3c-8c00-40b2fa7329bc)

I've also noticed that there is no `import` example in the resource documentation.
Would it be possible to add examples to each resource page to support those bringing unmanaged resources into terraform control?

**Comment by nirarg** [comment]
Hi @OurFriendIrony ,

Thank you for your comment.

Please notice that the old resources names are presented only when you use the old and deprecated ocm registry link (https://registry.terraform.io/providers/terraform-redhat/ocm/latest/docs/resources/cluster_rosa_classic)
When the right rhcs registry link is used, the resources are right, see: https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/resources/cluster_rosa_classic

Currently the import action is not supported, the relevant examples will be added once it will be supported.
