### ISSUE TITLE
rhcs assume on cluster creation not working as expected

### ISSUE THREAD

**Issue by OurFriendIrony** [terraform-redhat/terraform-provider-rhcs#182]
`rhcs 1.1.0`

I am trying to reimplement my rosa cluster creation using the provider instead of manually via the CLI, but am receiving the following issue.

```
module.rosa_cluster_2.rhcs_cluster_rosa_classic.cluster: Creating...
╷
│ Error: Can't build cluster
│
│   with module.rosa_cluster_2.rhcs_cluster_rosa_classic.cluster,
│   on .terraform/modules/rosa_cluster_2/cluster.tf line 1, in resource "rhcs_cluster_rosa_classic" "cluster":
│    1: resource "rhcs_cluster_rosa_classic" "cluster" {
│
│ Can't build cluster with name 'rosa-nonprod-x', failed while validating
│ account roles: Could not get Role
│ 'arn:aws:iam::XXXXXX:role/ManagedOpenShift-Installer-Role' :
│ AccessDenied: User:
│ arn:aws:sts::XXXXXX:assumed-role/RS_Admin/Steve.Stevens@rsgroup.com
│ is not authorized to perform: iam:GetRole on resource: role
│ ManagedOpenShift-Installer-Role because no identity-based policy allows the
│ iam:GetRole action
│       status code: 403, request id: bc58fc99-e547-4579-ac9a-211d521a4d58
╵
```

for reference, my provider configuration is as follows:
```
terraform {
  required_version = ">= 1"
  backend "s3" {}
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.5.0"
    }
    rhcs = {
      source  = "terraform-redhat/rhcs"
      version = "= 1.1.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
  assume_role {
    role_arn = "arn:aws:iam::${var.account_id}:role/${var.sts_prefix}"
  }
}

provider "rhcs" {
  token = data.vault_generic_secret.redhat.data["token"]
}
```

You'll note that when talking to the AWS provider, an `assume_role` is added so that my user assumes the role of an account specific role that manages resources in that account.

When running with the `rosa` cli (1.2.15) I would also perform this assume in order to action the cluster create, example:
```
echo "[profile ${PROFILE}]" > ~/.aws/config
echo "credential_source=Ec2InstanceMetadata" >> ~/.aws/config
echo "region=${PROFILE}" >> ~/.aws/config
echo "output=json" >> ~/.aws/config
echo "role_arn=arn:aws:iam::${ACCOUNT_ID}:role/${STS_PREFIX}" >> ~/.aws/config

rosa create cluster --profile="${PROFILE}" --region="${REGION}" ............
```

However, having switched over to using the rhcs provider I seem to fail to assume the appropriate role in order to apply changes.

I am missing something for transitioning from manual execution to the rhcs provider?

**Comment by nirarg** [comment]
Hi @OurFriendIrony ,

Thank you for your feedback.

The error you had caused from a limitation we have in version 1.1.0, in which the the rosa_cluster_resource code use the aws account configured on your local machine, for validations in the AWS account.
In order to avoid this error, make sure that the AWS account configured on your computer is the same account you provided to the AWS provider and used for the OCP cluster creation.

There is already PR in progress, that is going to remove those validations in the code (https://github.com/terraform-redhat/terraform-provider-rhcs/pull/190).
It would be released for next version (1.2.0)

Thanks,
Nir

**Comment by OurFriendIrony** [comment]
Hi @nirarg,
Thanks for getting back to me so quickly. I look forward to trying it!

**Comment by OurFriendIrony** [comment]
Hi @nirarg, I've noticed the above has been merged in, but `1.2.0` is not yet available.
I assume there is a lead time before publishing?

**Comment by nirarg** [comment]
Hi @OurFriendIrony ,

`1.2.0` version is going to be publish in about 2 weeks.
For the meanwhile, to solve you issue, you need to make sure the locally AWS credentials are the right one.
If you can you want, you also can build the main branch and run it locally from your machine.

Does it work for you? please let me know if you have any other issue

**Comment by OurFriendIrony** [comment]
@nirarg, ah I see. Thanks for the info.
Due to the makeup of our pipeline and the complexity of our AWS policies, it's not practical to set local credentials.
However, I'll run a make and try the current build locally.
Thanks!
