### ISSUE TITLE
Breaking typo in documentation

### ISSUE THREAD

**Issue by erchpm** [terraform-redhat/terraform-provider-rhcs#188]
Under *AWS permissions*, a resource name erroneously includes a special character: "arn:aws:secretsmanager:*:㊙*". This should be updated.

**Comment by nirarg** [comment]
Hi @erchpm ,
Thank you for the feedback

@EricPonvelle please check this

**Comment by nirarg** [comment]
This issue was fixed in PR https://github.com/terraform-redhat/terraform-provider-rhcs/pull/348

Closing this issue
