### ISSUE TITLE
Terraform provider with version 1.0.0 does not work with error 404 Not Found returned from github.com

### ISSUE THREAD

**Issue by vamsinm** [terraform-redhat/terraform-provider-rhcs#19]
Terraform provider with version 1.0.0 does not work. it looks like [gitlab project](https://github.com/terraform-redhat/terraform-provider-ocm/releases) only have release version v0.0.1 not v1.0.0

```
terraform {
  required_providers {
    ocm = {
      source = "terraform-redhat/ocm"
      version = "1.0.0"
    }
  }
}
```
Error: 
```
Error: Failed to install provider
│
│ Error while installing terraform-redhat/ocm v1.0.0: could not query
│ provider registry for registry.terraform.io/terraform-redhat/ocm: failed to
│ retrieve authentication checksums for provider: 404 Not Found returned from
│ github.com
```

switching to version 0.0.1 works

```
terraform {
  required_providers {
    ocm = {
      source = "terraform-redhat/ocm"
      version = "0.0.1"
    }
  }
}
```

**Comment by bardielle** [comment]
We requested the removal of version 1.0.0 from the Terraform registry. However, Terraform Registry saves the history and does not have the option to sync with removed GitHub releases, which appears to be a common issue. 
I contacted Terraform registry support and opened a ticket to remove version 1.0.0. 
In the meantime, please use version 0.0.1 explicitly.

`terraform {
  required_providers {
    ocm = {
      version = "0.0.1"
      source  = "terraform-redhat/ocm"
    }
  }
}`

**Comment by jjulien** [comment]
With the reset of this provider to 0.0.1, are there plans to remove the prior versioned tags and releases that are greater than 0.0.1 but behind 0.0.1 in the commit history?

For example, v0.1.9 comes before 0.0.1.

**Comment by bardielle** [comment]
Yes, we need to reset the tags. 
I will work on it

**Comment by nirarg** [comment]
We have already moved to newer versions
This is not relevant any more
Closing this issue
