### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by OurFriendIrony** [terraform-redhat/terraform-provider-rhcs#206]
Is there a release schedule for this provider?  
I'm waiting on version `1.2.0` to fix an issue in my deployments and am curious as to when it might be available?

**Comment by nirarg** [comment]
Hi @OurFriendIrony ,
Sorry for missing this message
version 1.2.2 is already available
You can find the change log here: https://github.com/terraform-redhat/terraform-provider-rhcs/blob/v1.2.2/CHANGELOG.md
This version also include removing the AWS API calls from the provider, as we discussed in previous issue
