### ISSUE TITLE
Examples contain misleading version restrictions

### ISSUE THREAD

**Issue by OurFriendIrony** [terraform-redhat/terraform-provider-rhcs#207]
Some of your [examples](https://github.com/terraform-redhat/terraform-provider-rhcs/blob/main/examples/create_account_roles/main.tf#L39) reference the sts module `terraform-redhat/rosa-sts/aws`.  
This module has a restriction to only support [version 4.x.x ](https://github.com/terraform-redhat/terraform-aws-rosa-sts/blob/main/main.tf#L5) of terraform, not >4.
Whilst that is not related to this provider directly, this projects examples [show >= 4.x.x](https://github.com/terraform-redhat/terraform-provider-rhcs/blob/main/examples/create_account_roles/main.tf#L21C7-L21C28) as being allowed. 

I am currently using `5.x.x` but cannot follow the examples due to the restriction in the sts module. I have raised an issue last week on that repo but have not met a response yet. https://github.com/terraform-redhat/terraform-aws-rosa-sts/issues/23

**Comment by nirarg** [comment]
Hi @OurFriendIrony ,
Thank you for the feedback
We work on improving the examples, targeting this as well

**Comment by OurFriendIrony** [comment]
Has any progress been made on this? I believe the module issue still hasn't received any responses highlighting any future changes

**Comment by nirarg** [comment]
Hi @OurFriendIrony ,

We are working on new module which also is going to contain all examples with improvements.
This is the new repository opened for this purpose:
https://github.com/terraform-redhat/terraform-rhcs-rosa
We will update here when this new module will be published

**Comment by OurFriendIrony** [comment]
Will this deprecate https://github.com/terraform-redhat/terraform-aws-rosa-sts/issues/23 ?

**Comment by nirarg** [comment]
Hi @OurFriendIrony 
Yes, finally the old module will be deprecated

If you need it for now, I can create quick fix changes the AWS version to ">=4.x.x", and release special module tag for this
You will have to change the module source version manually in the examples you use
In case you want this change, what is the module version you use?

**Comment by OurFriendIrony** [comment]
No it is fine, I can move over to the new module.
Thanks.

**Comment by nirarg** [comment]
This was fixed in [rosa-sts module](https://registry.terraform.io/modules/terraform-redhat/rosa-sts/aws/latest) in version 0.0.14
Also new module is in work in progress already with this issue solved

Closing this issue
