### ISSUE TITLE
Error putting S3 policy: AccessDenied

### ISSUE THREAD

**Issue by fabian-born** [terraform-redhat/terraform-provider-rhcs#220]
I used the `examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config` to create a ROSA cluster. 

I got following error message during creating the S3 bucket. I have no clue which right is missing:

```
│ Error: Error putting S3 policy: AccessDenied: Access Denied
│ 	status code: 403, request id: xxxx, host id: crypted_host_id
│ 
│   with module.oidc_config.module.oidc_config_input_resources[0].module.rosa_oidc_config_resources[0].aws_s3_bucket_policy.allow_access_from_another_account,
│   on .terraform/modules/oidc_config.oidc_config_input_resources/oidc_config_resources/create_s3_bucket.tf line 21, in resource "aws_s3_bucket_policy" "allow_access_from_another_account":
│   21: resource "aws_s3_bucket_policy" "allow_access_from_another_account" {

```

Configuration:
- Using previously-installed hashicorp/aws v4.67.0
- Using previously-installed terraform-redhat/rhcs v1.2.0-prerelease.1

Any idea?

**Comment by nirarg** [comment]
Hi @fabian-born ,
Have you created rosa cluster on this account before?
If not, make sure you have Completed [the ROSA getting started](https://console.redhat.com/openshift/create/rosa/getstarted) requirements 

Have you tried also to use the `examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config`?
