### ISSUE TITLE
Terraform run or import failing after configuring 'additional-trust-bundle-file'

### ISSUE THREAD

**Issue by vamsinm** [terraform-redhat/terraform-provider-rhcs#223]
Terraform run or import failing after configuring 'additional-trust-bundle-file' :

Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Stack trace from the terraform-provider-rhcs_v1.2.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xf863cb]
goroutine 84 [running]:
github.com/terraform-redhat/terraform-provider-rhcs/provider.populateRosaClassicClusterState({0x14c7f60, 0xc00037f240}, 0xc001[303](https://sfgitlab.opr.statefarm.org/rosa/terraform/clusters/rosamgmt/-/jobs/78741231#L303)200, 0xc00100a700, {0x14c31c0, 0x1d3e068})
	github.com/terraform-redhat/terraform-provider-rhcs/provider/cluster_rosa_classic_resource.go:1732 +0x188b
github.com/terraform-redhat/terraform-provider-rhcs/provider.(*ClusterRosaClassicResource).Read(0xc0014d8a60, {0x14c7f60, 0xc00037f240}, {{{{0x14cabc8, 0xc00111aba0}, {0x10ecf00, 0xc0014d7ad0}}, {0xc0014d6930, 0x0, 0x0, ...}}, ...}, ...)
	github.com/terraform-redhat/terraform-provider-rhcs/provider/cluster_rosa_classic_resource.go:1014 +0x492
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).readResource(0xc000116f90, {0x14c7f60, 0xc00037f240}, 0xc00037f100, 0xc000151980)
	github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/serve.go:571 +0x9bb
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).ReadResource(0x14c7f60?, {0x14c7f60?, 0xc00037f000?}, 0x5?)
	github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/serve.go:506 +0x86
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000220f00, {0x14c8008?, 0xc0014d61e0?}, 0xc0014e20c0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov6/tf6server/server.go:554 +0x33c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x123fb20?, 0xc000220f00}, {0x14c8008, 0xc0014d61e0}, 0xc0014e2060, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:345 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00039fc00, {0x14cb3e8, 0xc0002c4480}, 0xc0014e4000, 0xc0001170e0, 0x1cfeb30, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00039fc00, {0x14cb3e8, 0xc0002c4480}, 0xc0014e4000, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x28a
Error: The terraform-provider-rhcs_v1.2.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by nirarg** [comment]
Hi @vamsinm ,
Thank you for the feedback

We will check this and will update you on the progress

**Comment by nirarg** [comment]
Jira ticket: [OCM-3125](https://issues.redhat.com/browse/OCM-3125)

**Comment by nirarg** [comment]
Hi,

this bug was already fixed for v1.2.3 and v1.3.0
I'm closing this issue
In case you have more concerns about this fix, please open new issue

Best Regards,
Nir
