### ISSUE TITLE
Terraform init error for operator roles 'Error: Invalid validation error message'

### ISSUE THREAD

**Issue by ChrisSmiles** [terraform-redhat/terraform-provider-rhcs#23]
On terraform init i receive this error relating to a missing full stop on the error message. It works once i add a full stop in the error message .terraform/modules/operator_roles/variables.tf and rerun the init.

Error: 
│ Error: Invalid validation error message
│ 
│   on .terraform/modules/operator_roles/variables.tf line 29, in variable "operator_roles_properties":
│   29:       error_message = "The list of operator roles should contains 6 elements"
│ 
│ The validation error message must be at least one full sentence starting with an uppercase letter and ending with a period or question mark.
│ 
│ Your given message will be included as part of a larger Terraform error message, written as English prose. For broadly-shared modules we suggest using a similar
│ writing style so that the overall result will be consistent.

Terraform code:
data "ocm_rosa_operator_roles" "operator_roles" {
  operator_role_prefix = var.operator_role_prefix[terraform.workspace]
  account_role_prefix  = var.account_role_prefix[terraform.workspace]
}

module "operator_roles" {
  source  = "terraform-redhat/rosa-sts/aws"
  version = "0.0.1"

  cluster_id                  = ocm_cluster_rosa_classic.rosa_sts_cluster.id
  rh_oidc_provider_thumbprint = lookup(ocm_cluster_rosa_classic.rosa_sts_cluster.sts, "thumbprint")
  rh_oidc_provider_url        = lookup(ocm_cluster_rosa_classic.rosa_sts_cluster.sts, "oidc_endpoint_url")
  operator_roles_properties   = data.ocm_rosa_operator_roles.operator_roles.operator_iam_roles

  depends_on = [
    ocm_cluster_rosa_classic.rosa_sts_cluster
  ]
}

**Comment by euanhume** [comment]
After some investigation, this issue is actually in a separate GitHub repository (https://github.com/terraform-redhat/terraform-aws-rosa-sts). Suggest we close this issue and fix via PR in the other repository.

**Comment by bardielle** [comment]
Merged
