### ISSUE TITLE
Invalid proxy's attribute assignment

### ISSUE THREAD

**Issue by am90670** [terraform-redhat/terraform-provider-rhcs#236]
Hi, 

When creating a STS classic cluster with the `http_proxy`, `https_proxy` and `no_proxy` attributes set I get the following error during planning:

```shell
 Error: Invalid proxy's attribute assignment

   with rhcs_cluster_rosa_classic.rosa_sts_cluster,
   on rosa.tf line 25, in resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster":
   25: resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" {
 
 Expected at least one of the following: http-proxy, https-proxy, additional-trust-bundle
```

The only way workarounds I have is 

- Set additional-trust-bundle but that results issue [229](https://github.com/terraform-redhat/terraform-provider-rhcs/issues/229)
- Define a variable proxy variable as follows:
   ```
     variable "proxy" {
        description = "Proxy configuration"

        type = object({    
          additional_trust_bundle = optional(string)
          http_proxy              = optional(string, "...")
          https_proxy             = optional(string, "...")
          no_proxy                = optional(string, "...")
        })

       default = {}
     }

     resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" {
         ... 
        proxy = var.proxy
        ...
     }
   ``` 

  setting additional_trust_bundle to null or "" results in the above error when `http_proxy`, `https_proxy` and `no_proxy` are specified.

I'm using Terraform v1.5.3 and rhcs provider 1.3.0.prerelease.1. Same behaviour using provider version 1.2.2 also.

**Comment by sagidayan** [comment]
Hi @am90670 👋🏽 

Thanks for taking the time to submit this issue.

Our team will look into it an update this issue as we go.

@nirarg , @amalykhi

**Comment by am90670** [comment]
Hi, the error is occurring in version 1.2.4 of  the provider. Reading the source code I believe the cause is the attribute validation function that is defined in `proxyValidators`  uses the values defined configuration only i.e. `diag := req.Config.GetAttribute(ctx, req.AttributePath, state)`.  Using the generated plan object i.e. `req.Plan.GetAttribute(ctx, req.AttributePath, state)` will allow the provider to see the default values set using `optional()` function.

**Comment by nirarg** [comment]
This issue is duplicated with https://github.com/terraform-redhat/terraform-provider-rhcs/issues/361

Closing this issue
