### ISSUE TITLE
Request for cluster data source

### ISSUE THREAD

**Issue by am90670** [terraform-redhat/terraform-provider-rhcs#237]
The `rhcs_cluster_rosa_classic` resource outputs 'api_url and `console_url` (and others) are not populated when the resource completes. They are populated when the Terraform configuration is applied again i.e. after the cluster has been created.  Can the provider be enhanced with a data source that can be used to lookup details of the cluster please.  For example:

```shell
data "rhcs_cluster_rosa_classic " {
  cluster_name = var.cluster_name 
}
```

Or for the outputs to be return by the `rhcs_cluster_wait` resource?

**Comment by nirarg** [comment]
Hi @am90670 ,
Thank you for your feedback
We will look into it and will update you on the progress

Best regards,
Nir

**Comment by nirarg** [comment]
Opened jira ticket: [OCM-3259](https://issues.redhat.com/browse/OCM-3259)

**Comment by navinisaac** [comment]
+1

I require this feature as well. It is cumbersome to have to run a `-refresh-only` to populate the `output` for `console_url`

**Comment by navinisaac** [comment]
@nirarg is there any update on this issue? The OCM-3259 issue you linked leads to an error page.

**Comment by nirarg** [comment]
Closing this ticket as it was already completed.
See PR for more details:
https://github.com/terraform-redhat/terraform-provider-rhcs/pull/489
