### ISSUE TITLE
`terraform destroy` on rhcs_cluster_rosa_classic.rosa_sts_cluster resource fails

### ISSUE THREAD

**Issue by navinisaac** [terraform-redhat/terraform-provider-rhcs#250]
```╷
│ Error: Value cannot be changed
│
│   with rhcs_cluster_rosa_classic.rosa_sts_cluster,
│   on main.tf line 80, in resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster":
│   80: resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" {
│
│ This attribute is blocked for updating
╵
```

I am unable to destroy the cluster via TF. Please advise.

**Comment by tshefi** [comment]
Hello @navinisaac 

Could it possibly be that after deploying the cluster you might have intently (or not) changed one of the cluster's immutable parameter values before attempting to destroy it? Or maybe changed the cluster using tools other than TF say OCM or ROSA CLI? 

Any additional background info you can provide, might help while I try to replicate the issue. 

1. Which version of TF/provider/OCP?
2. Which cluster did you deploy: Rosa STS classic, OIDC managed or OIDC unmanaged? 
3. Would it be possible to share TF files (main.tfm, variables.tf, terraform.tfvars, tfstate) less private data, here directly or  privately with me?  

Tzach

**Comment by navinisaac** [comment]
Hi @tshefi, thank you for the quick response.

I believe the only thing I am changing (via rosa-cli) after the cluster is deployed via TF is granting users access to the cluster. I am using AzureAD as an identity provider with the OpenID Connect parameter. 

`rosa grant user cluster-admin --user=$user --cluster $CLUSTER_NAME --profile $AWS_PROFILE_NAME`

1. Which version of TF/provider/OCP?
```
Terraform v1.5.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/terraform-redhat/rhcs v1.2.2

cluster version is 4.12.28
```
2. Which cluster did you deploy: Rosa STS classic, OIDC managed or OIDC unmanaged?
```
Rosa STS classic, OIDC unmanaged

3. I can provide those if still required.

**Comment by tshefi** [comment]
Which tool/method did you use to configure AzureAD OpenIDC, TF or ROSA CLI? 
It's also supported via TF  despite missing an example (/examples/create_identity_provider/openid), yet another on my  todo list items.

**Comment by navinisaac** [comment]
I have used TF:

```
resource "rhcs_identity_provider" "oidc" {
  name           = "AzureAD"
  cluster        = rhcs_cluster_rosa_classic.rosa_sts_cluster.id
  mapping_method = "claim"
  openid = {
    claims = {
      email              = ["email"]
      name               = ["name"]
      preferred_username = ["upn"]
    }
    extra_scopes  = ["profile", "email"]
    issuer        = var.issuer_url
    client_id     = data.aws_ssm_parameter.clientid.value
    client_secret = data.aws_ssm_parameter.clientsecret.value
  }
}

**Comment by navinisaac** [comment]
Hey @tshefi,

Your AzureAD OpenIDC TF config, did you run it post cluster creation on a separate main.tf, or did you bundle cluster creation together with IDP config on same main.tf ?

```
It is in a different file called idp.tf

├── create_cluster.tf
├── create_roles.tf
├── env.sh
├── idp.tf
├── init.tf
├── output.tf
├── terraform.tfvars
└── variables.tf
```

Did your cluster happen to start an update/upgrade cycle?
```
I don't believe it did, would that happen without intervention?
``` 

I've attached the `tf.log` of the delete, hopefully thats helpful. 

Thanks again.
[tf.log](https://github.com/terraform-redhat/terraform-provider-rhcs/files/12445388/tf.log)

**Comment by navinisaac** [comment]
Hi @tshefi,

An update on my progress here, I was able to create a cluster, make changes to it, and ultimately tear it down with `terraform destroy`

Unfortunately, I did do a couple things differently so I'm not sure which change was effective, but seems like what you mentioned about an upgrade cycle could be the cause.

Here's what I did add:

I was not passing in `openshift_version` before (neither for role creation module or cluster creation resource)

I also was not passing in `availability_zones`. 

Now my tfvars looks like this:
```
aws_profile = "rosa"
cluster_name = "demo-v7"
aws_private_link = false
autoscaling = true
multi_az = true
machine_cidr = "10.20.0.0/16"
min_replicas = 3
max_replicas = 6
availability_zones = ["ca-central-1a", "ca-central-1b", "ca-central-1d"]
rosa_openshift_version = "4.13"
ocp_version = "4.13.9"
```
I noticed another open issue that said role creation needed `x.y` versioning and cluster creation needed `x.y.z`. Is it necessary to pass both or only the ocp_version is enough?

The other thing I did was move the contents of the `idp.tf` file into the `create_cluster.tf` file so it is one contiguous file.

The only other thing left is the issue of the `console_url` not being output at the end of cluster creation. However, that is referenced in this https://github.com/terraform-redhat/terraform-provider-rhcs/issues/237 thread and looks like there is an OCM Jira ticket for this.

Thank you for your assistance on the issue.

Navin

**Comment by bardielle** [comment]
@tshefi thank you for your help
@navinisaac it seems we should add the attribute that was changed and must not be changed, to the error
Also, it seems you changed the AZs which should not be changed 
https://github.com/terraform-redhat/terraform-provider-rhcs/blob/main/provider/cluster_rosa_classic_resource.go#L310

According to your question about versioning - can you refer to the main.tf file you're using?

**Comment by navinisaac** [comment]
Hi @bardielle,

There isn't a `main.tf` per se, but two files instead called create_roles.tf and create_cluster.tf.
I have attached them.
[Archive.zip](https://github.com/terraform-redhat/terraform-provider-rhcs/files/12523456/Archive.zip)

**Comment by bardielle** [comment]
@navinisaac Did terraform destroy worked at last?

**Comment by navinisaac** [comment]
Hi @bardielle , yes it did eventually work.
