### ISSUE TITLE
RHCS Terraform provider should use Terraform SDKv2

### ISSUE THREAD

**Issue by arendej** [terraform-redhat/terraform-provider-rhcs#260]
RHCS Terraform provider should use Terraform SDKv2

**Comment by arendej** [comment]
quick question: why not Terraform framework?

**Comment by am90670** [comment]
HashiCorp recommend using the framework over SDKv2. They aslo recommend migrating plugins using SDKv2 to the frame. See [Terraform Plugin SDKv2](https://developer.hashicorp.com/terraform/plugin/sdkv2).

**Comment by nirarg** [comment]
The terraform sdk version was updated for latest framework version
Main branch already include this change
This change would be included in v1.4.x release

Thank you for raising this issue.
Closing it, please open new issue in case of any related issue
