### ISSUE TITLE
Use of the resource rhcs_dns_domain

### ISSUE THREAD

**Issue by am90670** [terraform-redhat/terraform-provider-rhcs#305]
Provider v1.4.0-prerelease-1 includes the `rhcs_dns_domain` resource.   Is there purpose of this resource to reserve a DNS domain to be used with `rhcs_cluster_rosa_classic.base_dns_domain` ?  A use case I have, frequently requires the creation and destruction of a cluster but requires the cluster to use the same domain to avoid additional steps to configure DNS conditional forwarding.  Can this resource be used to support this use case?

[Issue 234](https://github.com/terraform-redhat/terraform-provider-rhcs/pull/234) mentions the `rhcs_dns_domain` resoucre  was created to support shared vpc feature. Can the resource be used for / in a standalone vpc also?

**Comment by nirarg** [comment]
Hi @am90670 ,

Using dns_domain not for shared vpc currently isn't supported from the terraform provider.
As far as I know there is plan to allow this for unmanaged clusters with bring your own vpc
@arendej @oriAdler please keep me ownest here

**Comment by oriAdler** [comment]
Currently, for unmanaged clusters, the user can provide dns_domain.
There is another effort, for managed clusters, to allow the user to provide dns_domain outside of the scope of shared VPC.

**Comment by bardielle** [comment]
@am90670 Does it answer your question? 
Any additional issue here? or can this issue be closed?
