### ISSUE TITLE
 Failed to install provider

### ISSUE THREAD

**Issue by JayavardhanTummidi** [terraform-redhat/terraform-provider-rhcs#31]
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding terraform-redhat/ocm versions matching "1.0.0"...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v4.57.1
╷
│ Error: Failed to install provider
│ 
│ Error while installing terraform-redhat/ocm v1.0.0: could not query provider registry for registry.terraform.io/terraform-redhat/ocm: failed to
│ retrieve authentication checksums for provider: 404 Not Found returned from github.com

**Comment by vamsinm** [comment]
@JayavardhanTummidi please take a look at [this](https://github.com/terraform-redhat/terraform-provider-ocm/issues/19#issuecomment-1429436658) comment

**Comment by nirarg** [comment]
We have already moved to newer versions
This issue was resolved
