### ISSUE TITLE
rhcs_cluster_rosa_classic outputs

### ISSUE THREAD

**Issue by OurFriendIrony** [terraform-redhat/terraform-provider-rhcs#327]
Could you please include the following outputs to the `rhcs_cluster_rosa_classic` or `rhcs_cluster_wait` resource:
- external nlb
- internal nlb
- classic elb

**Comment by bardielle** [comment]
Those attributes might be part of the default_ingress day2 resource. @gdbranco  @tsorya What do you think?

**Comment by bardielle** [comment]
This information is now available in the default ingress resource (only for ocp version >= 4.14) as part of the new release version v1.5.0
@OurFriendIrony can you approve it and close the issue?
