### ISSUE TITLE
Unable to upgrade cluster version

### ISSUE THREAD

**Issue by ChrisSmiles** [terraform-redhat/terraform-provider-rhcs#33]
When trying to upgrade the version of the rosa cluster, i receive the following error. 

│ Error: Value cannot be changed
│ 
│   with ocm_cluster_rosa_classic.rosa_sts_cluster,
│   on cluster.tf line 30, in resource "ocm_cluster_rosa_classic" "rosa_sts_cluster":
│   30:   version             = var.opc_version[terraform.workspace]
│ 
│ This attribute is blocked for updating

**Comment by euanhume** [comment]
To update further to this, attempting to upgrade a version of an existing ROSA cluster created by this provider this not possible currently due the "version" attribute being immutable. Suspect this is due to functionality not being available because AWS currently don't support managed policies. (https://github.com/terraform-redhat/terraform-provider-ocm/blob/main/provider/cluster_rosa_classic_resource.go#L338)

**Comment by tshefi** [comment]
I could be wrong here but suspect that upgrades only really started to work properly after [this](https://github.com/terraform-redhat/terraform-provider-rhcs/pull/94) which was merged at the end of May, after your failed upgrade attempt. 

Let me know which OCP version you had initially installed and which version you opted to upgrade to, I could recheck if still needed.

**Comment by tshefi** [comment]
From a Windows 10 system, successfully created account roles and deployed an OIDC managed cluster OCP 4.13.5 
Using versions:



rhcs_cluster_wait.rosa_cluster: Creation complete after 28m14s

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

cluster_id = "25ejrtekdoi0m59qq3md0um08r213kdr"
oidc_config_id = "25ejp50cqcvvci76k50nus1b1cc6e13b"
oidc_endpoint_url = "[d3gt1gce2zmg3d.cloudfront.net/25ejp50cqcvvci76k50nus1b1cc6e13b](http://d3gt1gce2zmg3d.cloudfront.net/25ejp50cqcvvci76k50nus1b1cc6e13b)"
thumbprint = "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"

**Comment by euanhume** [comment]
Thanks for the update. You are correct, cluster upgrades were only available after the failed attempt so please consider this issue resolved. Are there plans to include cluster upgrade schedules into the terraform provider for cluster upgrades i.e. the `--schedule-date` and `--schedule-time` options from the CLI?

**Comment by tshefi** [comment]
@nirarg Any idea if we plan to support cluster upgrade scheduling ?

**Comment by bardielle** [comment]
The upgrade doesn't include support `scheduled upgrade` for now.

**Comment by bardielle** [comment]
@ChrisSmiles can we close that issue?

**Comment by nirarg** [comment]
Closing this issue
@ChrisSmiles in case you have any issue related, please open new issue
