### ISSUE TITLE
AWS Shared VPC

### ISSUE THREAD

**Issue by zenobiozz** [terraform-redhat/terraform-provider-rhcs#337]
I would like to know if is possible launch the cluster using a shared VPC as rosa cluster command can do, for example:

rosa create cluster XXXXXX

--shared-vpc-role-arn  XXX

So in theory only I need to send the subnets id and the role that give access to create the resources
Thanks!

**Comment by nirarg** [comment]
Hi @zenobiozz ,

Thank you for reaching out for this
Yes, rosa classic cluster can be created with shared VPC
Make sure to create the shared VPC role with the pre-created DNS base domain, very similar to the way it done in the CLI.

We are working on adding examples and documentation for this scenario, I will update here once we have something ready.

Best regards,
Nir

**Comment by bardielle** [comment]
This feature was released in the last TF version v1.5.0
Closing that issue
