### ISSUE TITLE
LDAP Validation Issue

### ISSUE THREAD

**Issue by jland-redhat** [terraform-redhat/terraform-provider-rhcs#341]
The LDAP schema validation for email seems to be incorrect.

So if I attempt to do something like:

```
  ldap = {
    url        = var.ldap_url
    attributes = {
      email                  = ["mail"]
      id                     = var.attribute_id
      name                   = var.attribute_name
      preferred_username     = var.attribute_preferred_username
    }
```

It will fail with "Invalid Email"

The backing code looks like this:
```
var ldapAttrSchema = map[string]schema.Attribute{
	"email": schema.ListAttribute{
		Description: "The list of attributes whose values should be used as the email address.",
		ElementType: types.StringType,
		Optional:    true,
		Validators: []validator.List{
			listvalidator.ValueStringsAre(
				stringvalidator.RegexMatches(common.EmailRegexp, "Invalid email"),
			),
		},
	},
```

The EmailRegexp basically says the value needs to look like an email (i.e. example@gmail.com). 

But that is generally not going to be the case because this is validating the LDAP Key, **not** the value of the email itself.

Should be a pretty simple fix I will try to create a quick PR

**Comment by nirarg** [comment]
Hi @jland-redhat ,
Thank you for the contribution

I'm not so familiar with the ldap identity provider, but do you say that email attribute not contains actual email address?

@sagidayan can you please review this and the PR?

**Comment by jland-redhat** [comment]
Yes I actually already created a PR with what I believe is the fix, hopefully explains it a little more

**Comment by sagidayan** [comment]
Thanks for opening the issue, and much more for opening the PR. Let's move the discussion there.

**Comment by nirarg** [comment]
@jland-redhat thank you for contributing this
I'm closing the issue
Feel free to re-open in case you think need further actions
