### ISSUE TITLE
Issue running TF Init due to missing rhcsprovider

### ISSUE THREAD

**Issue by hhh0505** [terraform-redhat/terraform-provider-rhcs#347]
I keep getting an error when trying to run a `Terraform init` using version 1.3.0 of provider

`╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/rhcs: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/rhcs
│
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules are currently depending on hashicorp/rhcs, run the following command:
│     terraform providers
`

**Comment by hhh0505** [comment]
issue on my end not passing required provider in each module.

**Comment by bardielle** [comment]
@hhh0505 can we close the issue?
