### ISSUE TITLE
Issue during terraform apply : getting error related to default_mp_labels parameter in rosa

### ISSUE THREAD

**Issue by vsomwanshi** [terraform-redhat/terraform-provider-rhcs#353]
Hi Team,

When i am executing terraform plan getting below output default_mp_labels parameter to be removed :

```
  # rhcs_cluster_rosa_classic.rosa will be updated in-place

  ~ resource "rhcs_cluster_rosa_classic" "rosa" {
      ~ api_url                  = "xxxxxxxxx" -> (known after apply)
      ~ base_dns_domain          = "xxxxxxxx" -> (known after apply)
      ~ ccs_enabled              = true -> (known after apply)
      ~ console_url              = "xxxxxxx" -> (known after apply)
      ~ current_version          = "4.13.4" -> (known after apply)
      - default_mp_labels        = {
          - "cluster.ocs.openshift.io/openshift-storage" = ""
        } -> null
      ~ domain                   = "xxxxxxx" -> (known after apply)
      ~ ec2_metadata_http_tokens = "optional" -> (known after apply)
        id                       = "xxxxxx"
      + max_replicas             = (known after apply)
      + min_replicas             = (known after apply)
        name                     = "xxxxxxxxxxx"
      ~ ocm_properties           = {
          - "rosa_creator_arn" = "xxxxxxxx"
          - "rosa_tf_commit"   = "xxxxxxxxxxxxxx"
          - "rosa_tf_version"  = "1.3.0"
        } -> (known after apply)
      ~ state                    = "ready" -> (known after apply)
        tags                     = {
            "owner" = "xxxxxxxxxxxxxx"
        }
        # (19 unchanged attributes hidden)
    }

```

When i apply terraform apply .... getting below error :

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to rhcs_cluster_rosa_classic.rosa, provider "provider[\"registry.terraform.io/terraform-redhat/rhcs\"]" produced an unexpected new value: .default_mp_labels: was null, but now
│ cty.MapVal(map[string]cty.Value{"cluster.ocs.openshift.io/openshift-storage":cty.StringVal("")}).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
Releasing state lock. This may take a few moments...
```

Below is my rhcs_cluster_rosa_classic configuration file :

```
resource "rhcs_cluster_rosa_classic" "rosa" {
  name = var.cluster_name

  cloud_region   = var.aws_region
  aws_account_id = data.aws_caller_identity.current.account_id
  tags           = local.tags

  replicas             = var.replicas
  availability_zones   = var.availability_zones
  aws_private_link     = var.enable_private_link
  aws_subnet_ids       = var.enable_private_link ? module.rosa-vpc.private_subnets : concat(module.rosa-vpc.private_subnets, module.rosa-vpc.public_subnets)
  compute_machine_type = var.compute_node_instance_type
  multi_az             = length(module.rosa-vpc.private_subnets) == 3 ? true : false
  version              = var.rosa_version
  machine_cidr         = module.rosa-vpc.vpc_cidr_block
  properties           = { rosa_creator_arn = data.aws_caller_identity.current.arn }
  sts                  = var.enable_sts ? local.sts_roles : null
  depends_on           = [module.rosa-vpc]
}
```

Here, i am not passing default_mp_labels anywhere explicitly in the configuration file.

Upon checking terraform state file could see this default_mp_labels parameter is applied :

```
"default_mp_labels": {
              "cluster.ocs.openshift.io/openshift-storage": ""
            },
```

I am using the same configuration for multiple clusters where default_mp_labels is set to null.

Can anyone help me on this.

**Comment by nirarg** [comment]
Hi @vsomwanshi,

Thank you for your report
Can you please add which terraform provider version was used?

**Comment by nirarg** [comment]
> I am using the same configuration for multiple clusters where default_mp_labels is set to null.

Is this error not reproduced in the other clusters?
Can you point on another differences between those clusters?

@ciaranRoche can you please advise on this?
Is there any case where OCM `Nodes().GetComputeLabels()` returns `"cluster.ocs.openshift.io/openshift-storage": ""` even when the user doesn't set it?
If this is the case, we need to set this attribute in terraform as `computed`

**Comment by vsomwanshi** [comment]
@nirarg  Below is the provider version that we are using for all the clusters :

```
terraform {

  required_providers {

    rhcs = {

      version = ">= 1.0.5"

      source  = "terraform-redhat/rhcs"

    }

    aws = {

      source  = "hashicorp/aws"

      version = "~> 4.0"

    }

  }

}
```

We don't see simiar error or change in other clusters. we don't see below parameter in other cluster terraform state file as well. 

```
Terraform state output from dev cluster where we are see this parameter  :

"current_version": "4.13.4",
"default_mp_labels": {
"cluster.ocs.openshift.io/openshift-storage": ""
},

Terraform state output from one of our other cluster where we don’t see this parameter :

"current_version": "4.13.12",
"default_mp_labels": null,

"current_version": "4.13.13",
"default_mp_labels": null,
```

**Comment by JohnStrunk** [comment]
> @ciaranRoche can you please advise on this? Is there any case where OCM `Nodes().GetComputeLabels()` returns `"cluster.ocs.openshift.io/openshift-storage": ""` even when the user doesn't set it? If this is the case, we need to set this attribute in terraform as `computed`

That particular label goes with the ODF product. I suspect it's being added by the ODF addon. IIRC, it's used to control which nodes the storage pods run on. We'll probably need to have a way to permit the label to exist even when the terraform config doesn't include it.

**Comment by vsomwanshi** [comment]
@JohnStrunk @nirarg Yesterday, when i was digging more in to our ROSA cluster, i found that these labels are applied on the nodes when we were trying to deploy the ODF in ROSA cluster. Later, RedHat confirmed ODF is not yet supported on ROSA.

Labels are existing on the node, can we delete them explicitly ? and that error will go away automatically ?

@JohnStrunk Yes you are correct, going forward when RedHat introduces ODF support on ROSA then terraform should permit this under "default_mp_labels" and if it shows as a change during terraform plan ( in case ODF applies this label on node) then terraform should permit to change it.

Currently, when i am trying to apply that change getting below error :

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to rhcs_cluster_rosa_classic.rosa, provider "provider[\"registry.terraform.io/terraform-redhat/rhcs\"]" produced an unexpected new value: .default_mp_labels: was null, but now
│ cty.MapVal(map[string]cty.Value{"cluster.ocs.openshift.io/openshift-storage":cty.StringVal("")}).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
Releasing state lock. This may take a few moments...
```

**Comment by nirarg** [comment]
> That particular label goes with the ODF product. I suspect it's being added by the ODF addon. IIRC, it's used to control which nodes the storage pods run on. We'll probably need to have a way to permit the label to exist even when the terraform config doesn't include it.

@JohnStrunk so we need to change this attribute to be computed in order to allow "computing" this label, am I right?

**Comment by vsomwanshi** [comment]
@nirarg I have removed the labels from the node manually due to which terraform rhcs provider was restricting to execute any operation on rhcs_cluster_rosa_classic.rosa module.

After removing the labels, i was able to perform the required operation and cluster looks good now.

**Comment by JohnStrunk** [comment]
> > That particular label goes with the ODF product. I suspect it's being added by the ODF addon. IIRC, it's used to control which nodes the storage pods run on. We'll probably need to have a way to permit the label to exist even when the terraform config doesn't include it.
> 
> @JohnStrunk so we need to change this attribute to be computed in order to allow "computing" this label, am I right?

The specific error w/ `default_mp_labels` that prompted this issue should be gone now that #228 merged. But, the problem will now be moved to the machine_pool resource. The `labels` attribute of `machine_pool` may exhibit this behavior.

I'll try to summarize my understanding, and we should decide on a path forward...

Situation:
- There is other software (in this case ODF) that may change node labels (current example applies, but it could also remove, these things could be one-time or an ongoing reconcile/enforcement)
- The user provides labels via their TF config

What should the result of the above be?
- The node could get the union of the above. The user could would provide "labels" in the config; we apply newly supplied ones, and we remove newly deleted ones, but we don't change labels the user hasn't mentioned.
- Should we provide a "computed" field that contains the actual labels on the node?
  - If not, and we go w/ the "delta" approach, above, the "other software" labels would be largely invisible to the TF config. This would mean users wouldn't be able to reference them in the rest of their declarative configuration.

This issue isn't really about whether a specific attribute is required/optional/computed, it's about what we want the experience to look like and how we take into account legitimate out-of-band changes (that probably need to be preserved).

**Comment by vsomwanshi** [comment]
@bardielle Actually as i mentioned earlier, I removed the labels from the node manually due to which terraform rhcs provider was restricting to execute any operation on rhcs_cluster_rosa_classic.rosa module.

After removing the labels, i was able to perform the required operation and cluster looks good now.

I am unable to test this scenario now, if anything occurs will get back to you. Thanks !!
