### ISSUE TITLE
Issue while running terraform init

### ISSUE THREAD

**Issue by sujith1594** [terraform-redhat/terraform-provider-rhcs#354]
Hi Team,

We are getting below error while running "terraform init". Below is the error message.

```
Error: Failed to install provider
│
│ Error while installing terraform-redhat/rhcs v1.4.0: archive has incorrect
│ checksum
│ zh:7c62966cfc1b4bdec11aab4be48f01af2c8770f3d5c8ec4e443cc35abb582fd5
│ (expected
│ zh:7ca32b7ccab07512a40993c9dfc872ae4f37845bb4f5386aa67192d02f68595a)
```
Adding this in required providers

```
terraform {
  required_providers {
    rhcs = {
      source = "terraform-redhat/rhcs"
      version = "1.4.0"
    }
  }
}

```
Can some one help me fix the issue?

Thanks,
Sujith.

**Comment by vsomwanshi** [comment]
@sujith1594 
Sometimes, the cached plugins can get corrupted. You can try clearing the Terraform cache to see if that resolves the problem. Run the following command to clear the Terraform cache

Hope you tried ```terraform init -reconfigure``` as well ?

**Comment by bardielle** [comment]
Hi @sujith1594 
I ran `terraform init` and it worked for me
Can you update your state?

**Comment by sujith1594** [comment]
Hi @vsomwanshi 
I tried "terraform init -reconfigure" still getting the same issue

**Comment by bardielle** [comment]
@sujith1594 Is this issue still relevant?

**Comment by sujith1594** [comment]
This has been fixed
