### ISSUE TITLE
Allow scheduling for upgrades

### ISSUE THREAD

**Issue by hhh0505** [terraform-redhat/terraform-provider-rhcs#358]
Currently you can set the new version which will upgrade, but there is no way to set the schedule timing similar to how you can with thee CLI (--schedule-date and --schedule-time flags.)

**Comment by nirarg** [comment]
The option for setting the schedule wasn't enabled in the terraform provider
@bardielle @JohnStrunk please keep me honest here
In case this is needed we will have to add it to the work plan

**Comment by JohnStrunk** [comment]
That's correct. The rationale was that terraform is designed around the notion that it should set the infrastructure to a particular state when it's run. As such, we felt that upgrades should be "immediate" when the desired version is changed.
I wouldn't have a TF config that says "create an EC2 instance tomorrow", so it doesn't really make sense to say "upgrade my cluster tomorrow." Instead, I'd run the config when I want those things to happen.

This is different than the rosa cli, where scheduling is supported. At some point, this may get added to TF, but the above is why it's not in the current feature set. Hope that helps.

**Comment by bardielle** [comment]
@hhh0505 Do you have any other comments or requests? Otherwise, can this issue be closed?

**Comment by hhh0505** [comment]
It can be closed, thank you for explaining the rationale behind this.
