### ISSUE TITLE
Missing infra_id and other attributes for cluster

### ISSUE THREAD

**Issue by RelicCornhusk** [terraform-redhat/terraform-provider-rhcs#374]
I'm trying to deploy a cluster that is compatible with the AWS Load Balancer Operator, and for that I need to tag my ROSA subnets and VPC with the value of the cluster's Infra ID. See step 3.1.4 in the [Red Hat documentation for the operator](https://access.redhat.com/documentation/en-us/red_hat_openshift_service_on_aws/4/html-single/networking/index). I'm currently unable to do that with Terraform as the `rhcs_cluster_rosa_classic` resource does not have the Infra ID as one of its attributes. It is also not available in the `rhcs_info` data source.

I would also like to request the addition of other cluster properties found through `rosa describe cluster -c <cluster-name>` to the provider, either as attributes to the cluster resource or as its own data source, since this will very likely be needed for more advanced use-cases.

**Comment by bardielle** [comment]
@RelicCornhusk Thank you for your feedback
I opened a relevant [PR](https://github.com/terraform-redhat/terraform-provider-rhcs/pull/402) for `cluster_rosa_classic` resource

About the suggestion for a new cluster's info data source, there is an opened PR and it will be released in v1.5.0

**Comment by tshefi** [comment]
Works as expected, tested using Danielle's fork, 
installed a managed oidc 4.14 cluster, added infra_id to Terraform's output.tf,
confirming identical values from rosa describe cluster and output.tf. 

$ tail output.tf 
..
output "infra_id" {
  value = rhcs_cluster_rosa_classic.rosa_sts_cluster.infra_id
}

terraform apply 
...
rhcs_cluster_rosa_classic.rosa_sts_cluster: Creation complete after 44m11s [id=27p60qja1c9fehimngj1hkkmuqsmtaa4]
Apply complete! Resources: 15 added, 0 changed, 0 destroyed.

Outputs:
cluster_id = "27p60qja1c9fehimngj1hkkmuqsmtaa4"
infra_id = "ts-2711-mfpf2"


$ rosa describe cluster -c ts-2711 | grep Infra
 - Infra:                   2
Infra ID:                   ts-2711-mfpf2

**Comment by bardielle** [comment]
@RelicCornhusk The v1.4.2 would be released on Dec 06

**Comment by bardielle** [comment]
Version v1.4.2 was released today.
Please update/ close the issue.
