### ISSUE TITLE
Error: `worker_disk_size` and `disk_size` not recognised

### ISSUE THREAD

**Issue by ovaleanu** [terraform-redhat/terraform-provider-rhcs#426]
Terraform version: v1.6.3
rhcs version: v1.4.1

The parameter `worker_disk_size` from [rhcs_cluster_rosa_classic](https://github.com/terraform-redhat/terraform-provider-rhcs/blob/6a233d87c6774ea9fea734bc6d393a450b808452/provider/clusterrosaclassic/cluster_rosa_classic_resource.go#L251C18-L251C18) resource is not recognized. The error is "Unexpected attribute: An attribute named `worker_disk_size` is not expected here".

The same for `disk_size` from [rhcs_machine_pool](https://github.com/terraform-redhat/terraform-provider-rhcs/blob/6a233d87c6774ea9fea734bc6d393a450b808452/provider/machinepool/machine_pool_resource.go#L196C9-L196C9) resource.

**Comment by bardielle** [comment]
The released version is v1.4.1 which doen't include those new attributes. 
You point into the main branch (would be released as v1.5.0)

**Comment by bardielle** [comment]
@ovaleanu can you verify it with the new version v1.5.0 please? 
If it's working for you please close the issue

**Comment by ovaleanu** [comment]
@bardielle all good.
