### ISSUE TITLE
ROSA Cluster Nodes, LB, Route53 resources not deleted using terraform destroy

### ISSUE THREAD

**Issue by manish-jangra** [terraform-redhat/terraform-provider-rhcs#528]
Hi Team, I created two ROSA Private clusters using `rhcs_cluster_rosa_classic`, but when I tried cleaning up the resources using `terraform destroy`. It only deleted the entry from OCM Organisation but aws resources like EC2 instances, Load Balancers, Route53 hosted zones and more were intact and were not deleted.

is that known yet?

**Comment by nirarg** [comment]
Hi @manish-jangra ,
Can you please share the `terraform destroy` logs here?

**Comment by manish-jangra** [comment]
I will try again and share the logs. I think the logs are gone with closing the terminal.

**Comment by manish-jangra** [comment]
@nirarg you can close this. I was probably deleting account-roles and operator-roles.

Thanks for your help.!
