### ISSUE TITLE
CLUSTERS-MGMT-400 error for HCP 

### ISSUE THREAD

**Issue by ahmad-sharif** [terraform-redhat/terraform-provider-rhcs#580]
I am getting the following error only for HCP creation for '1.6.0-prerelease.1'. 
Can't create cluster with name 'test': status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is 'b568b495-8253-4e33-9269-000000': Attribute 'aws.access_key_id' is mandatory

I have tried a few options
1. configuring AWS config
2.  exporting AWS creds as env variable
3. exporting AWS creds with TF_VAR_ the prefix

**Comment by gdbranco** [comment]
Hello there, you are probably missing to add sts field to your terraform setup. HCP clusters are required to use the STS settings. On '1.6.0-prerelease.2' the field will also be set as required within our provider, prerelease.2 should be available soon
