### ISSUE TITLE
Need to change the default worker pool instance type

### ISSUE THREAD

**Issue by vsomwanshi** [terraform-redhat/terraform-provider-rhcs#685]
Hi Team,

We have deployed the cluster with below configuration.

```
resource "rhcs_cluster_rosa_classic" "rosa" {
  name = var.cluster_name

  cloud_region   = var.aws_region
  aws_account_id = data.aws_caller_identity.current.account_id
  tags           = local.tags

  replicas             = var.replicas
  availability_zones   = var.availability_zones
  aws_private_link     = var.enable_private_link
  private              = var.private
  aws_subnet_ids       = var.enable_private_link ? module.rosa-vpc.private_subnets : concat(module.rosa-vpc.private_subnets, module.rosa-vpc.public_subnets)
  compute_machine_type = var.compute_node_instance_type
  multi_az             = length(module.rosa-vpc.private_subnets) == 3 ? true : false
  version              = var.rosa_version
  machine_cidr         = module.rosa-vpc.vpc_cidr_block
  properties           = { rosa_creator_arn = data.aws_caller_identity.current.arn }
  sts                  = var.enable_sts ? local.sts_roles : null
  depends_on           = [module.rosa-vpc]

  # Pass the upgrade_acknowledgements_for parameter here
  upgrade_acknowledgements_for = var.upgrade_acknowledgements_for
}
```

Variables values for reference :

```
cluster_name                  = "rosa-dev"
rosa_version                  = "4.13.41"
upgrade_acknowledgements_for  = "4.13"
replicas                      = "3"
enable_private_link           = "false"
private                       = "false"
compute_node_instance_type    = "m5.xlarge"
```

While deploying the cluster worker nodes are deployed with `m5.xlarge`, According to current workload this instanace_type is not enough for us so we are seeking for a solution to change the instance type from `m5.xlarge` to some other higher configuration. e.g `m5.4xlarge, m5.8xlarge`.

Is this possible via terraform directly followed by changing the variable `compute_node_instance_type` ?

if so, will it `cordon, drain and powere off` the nodes and then change the instance_type and `power on  and uncordon` the nodes because as per my knowledge we need to power off the instance to change the instance_type.

I tried to changing the values and execute the terraform plan and which is showing me 1 to change but i'm little concern about the behaviour of the cluster post terraform applying ?

```
  # rhcs_cluster_rosa_classic.rosa will be updated in-place
  ~ resource "rhcs_cluster_rosa_classic" "rosa" {
      + admin_credentials            = (known after apply)
      ~ api_url                      = "https://api.xxxxxx-rosa-dev.qrvr.p1.openshiftapps.com:6443" -> (known after apply)
      ~ ccs_enabled                  = true -> (known after apply)
      ~ compute_machine_type         = "m5.xlarge" -> "m5.8xlarge"
      ~ console_url                  = "xxxxxxxxx" -> (known after apply)
      ~ current_version              = "4.13.41" -> (known after apply)
      ~ domain                       = "xxxxxxxxx" -> (known after apply)
        id                           = "xxxxxxxxo"
      ~ infra_id                     = "xxxxxxx-rosa-dev-kb9fx" -> (known after apply)
        name                         = "xxxxxxx-rosa-dev"
      ~ ocm_properties               = {
          - "rosa_creator_arn" = "xxxxxxxx"
          - "rosa_tf_commit"   = "xxxxx"
          - "rosa_tf_version"  = "1.6.2"
        } -> (known after apply)
      ~ state                        = "ready" -> (known after apply)
        tags                         = {
            "owner" = "xxxxxxx"
        }
        # (21 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Really appreciated your response.

Thanks in advance !!

**Comment by nirarg** [comment]
Hi @vsomwanshi ,
The `compute_machine_type` variable cannot be changed after the cluster creation.
I order to change it, you need to replace the default MachinePool, with the following steps:
1. Create new MachinePool with the required MachineType
2. Make sure you have the minimum machines replicas before you delete the default MachinePool
3. Import the Default Machine Pool terraform resource
4. Delete the  Default Machine Pool terraform resource

This will include moving all your instances to new instances in the new MachinePool.

/cc @gdbranco @ciaranRoche

**Comment by vsomwanshi** [comment]
@nirarg You want me to import the default worker pool in terraform state like this

```
terraform import --var-file datacenter/aws_account/sre/sre.tf "<resource>" cluster_id,worker_pool_name
```

I think this is feasible when we have manually created a machine pool and we can import using specific `machine_pool` module.

e.g.
```
# Module to create a worker machine pool
resource "rhcs_machine_pool" "machine_pool" {
#  count                             = length(var.worker_pool_names)
  count                             = length(var.worker_pool_names) > 0 ? length(var.worker_pool_names) : 0
  cluster                           = rhcs_cluster_rosa_classic.rosa.id
  name                              = var.worker_pool_names[count.index]
  machine_type                      = var.worker_pool_machine_type
  replicas                          = var.worker_pool_replicas
  disk_size                         = var.worker_disk_size
}
```

In our case, default machine pool got created from module `rhcs_cluster_rosa_classic`

```
resource "rhcs_cluster_rosa_classic" "rosa" {
  name = var.cluster_name

  cloud_region   = var.aws_region
  aws_account_id = data.aws_caller_identity.current.account_id
  tags           = local.tags

  replicas             = var.replicas
  availability_zones   = var.availability_zones
  aws_private_link     = var.enable_private_link
  private              = var.private
  aws_subnet_ids       = var.enable_private_link ? module.rosa-vpc.private_subnets : concat(module.rosa-vpc.private_subnets, module.rosa-vpc.public_subnets)
  compute_machine_type = var.compute_node_instance_type
  multi_az             = length(module.rosa-vpc.private_subnets) == 3 ? true : false
  version              = var.rosa_version
  machine_cidr         = module.rosa-vpc.vpc_cidr_block
  properties           = { rosa_creator_arn = data.aws_caller_identity.current.arn }
  sts                  = var.enable_sts ? local.sts_roles : null
  depends_on           = [module.rosa-vpc]

  # Pass the upgrade_acknowledgements_for parameter here
  upgrade_acknowledgements_for = var.upgrade_acknowledgements_for
}
```

So, how can we import that default worker pool.

**Comment by nirarg** [comment]
The default Machine Pool is created as part of the cluster, but it can be imported separately from the cluster using the "machine_pool" resource.

The default Machine Pool, named "worker," is automatically created as part of the cluster. During cluster creation, this Machine Pool is "owned" by the cluster. After the cluster creation is completed, users must import it as a new resource in the Terraform manifest to manage or delete it. This can be done using the regular Terraform import command or the "Magic import."

The "Magic import" is a special behavior implemented in the machine_pool resource (in the apply action). If users add a "machine_pool" resource with the unique name "worker," it tries to "import" it instead of creating a new one. The "Magic import" allows users to add the "machine_pool" to the Terraform manifest from the start, enabling it to be created and imported automatically in a single apply action.

For more information see [Default Machine Pool documentation](https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/guides/worker-machine-pool)

**Comment by vsomwanshi** [comment]
@nirarg Thank you so much for such comprehensive information, which has really helped boost my knowledge.

One last question: Once we import the default worker machine pool, is it possible to change the machine instance type for these worker nodes?

**Comment by nirarg** [comment]
The `machine_type` attribute can't be changed after the `machine_pool` creation.
See the [machine_pool resource documentation](https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/resources/machine_pool#machine_type) for more information.
In order to use different `machine_type`, need to create new `machine_pool` to replace the existing one.

**Comment by vsomwanshi** [comment]
@nirarg Thank you so much for the fruitful information.

It really helped me to solve my scenario
