### ISSUE TITLE
ec2_metadata_http_tokens is missing in resource rhcs_cluster_rosa_hcp

### ISSUE THREAD

**Issue by hoadn147** [terraform-redhat/terraform-provider-rhcs#741]
how to enable ec2_metadata_http_tokens in rhcs_cluster_rosa_hcp, i see that option inside the test but for version v1.6.2 dont have that option

**Comment by dheepansn** [comment]
+1
Please let us know. We would like to implement ROSA-HCP with `ec2_metadata_http_tokens`

**Comment by gdbranco** [comment]
[Version 1.6.3 will be including the support](https://github.com/terraform-redhat/terraform-provider-rhcs/blob/main/CHANGELOG.md) and is currently undergoing release candidate test compliance

**Comment by gdbranco** [comment]
Closing as the field is not included in v1.6.3+, if needed please reopen the issue with more information
