### ISSUE TITLE
Creation of rosa classic cluster fails on trust relationship

### ISSUE THREAD

**Issue by psmyth-entertainment** [terraform-redhat/terraform-provider-rhcs#77]
Attempting to create a rosa cluster using: https://github.com/terraform-redhat/terraform-provider-ocm/tree/main/examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster 

I have already existing account roles created when I created a rosa cluster using the rosa cli. When I run terraform apply I get the following error:

│ Error: Can't create cluster
│ 
│   with ocm_cluster_rosa_classic.rosa_sts_cluster,
│   on main.tf line 38, in resource "ocm_cluster_rosa_classic" "rosa_sts_cluster":
│   38: resource "ocm_cluster_rosa_classic" "rosa_sts_cluster" {
│ 
│ Can't create cluster with name 'tooling-uat': status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is
│ '[redacted]: Failed to assume role with ARN 'arn:aws:iam::[redacted]:role/ManagedOpenshift-Installer-Role': failed to assume role: operation error
│ STS: AssumeRole, https response error StatusCode: 403, RequestID: [redacted], api error AccessDenied: User:
│ arn:aws:sts::[redacted]:assumed-role/RH-Managed-OpenShift-Installer/OCM is not authorized to perform: sts:AssumeRole on resource:
│ arn:aws:iam::[redacted]:role/ManagedOpenshift-Installer-Role

The role trust relationship is as follows:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::[redacted]:role/RH-Managed-OpenShift-Installer"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}

The redacted portions match of course

**Comment by psmyth-entertainment** [comment]
I've resolved this by creating new account roles but should someone not wish to do so, this is still a problem

**Comment by OurFriendIrony** [comment]
I am also having this issue.
Did you introduce a custom role to resolve or one generated with the rosa cli?

**Comment by psmyth-entertainment** [comment]
In the end I just created new account roles with a block like this

module "create_account_roles" {
  source  = "terraform-redhat/rosa-sts/aws"
  version = "0.0.5"

  create_operator_roles = false
  create_oidc_provider  = false
  create_account_roles  = true

  account_role_prefix    = local.role_prefix
  ocm_environment        = "production"
  rosa_openshift_version = module.vars.env.openshift_version # We use an in-house module to set vars per env
  account_role_policies  = data.ocm_policies.all_policies.account_role_policies
  operator_role_policies = data.ocm_policies.all_policies.operator_role_policies
}

data "ocm_policies" "all_policies" {}

**Comment by nirarg** [comment]
Hi @psmyth-entertainment & @OurFriendIrony ,

Thank you for your feedback and sorry for the late response on this
I tried to reproduce this issue:
1. create account roles from the CLI (`rosa create account-roles --prefix nargaman-rosa-account --version 4.13`)
2. Create rosa cluster (managed OIDC) with the same account role prefix, to use the account role created from the CLI

The issue wasn't reproduced to me,
Can you please give me more details how the resources were created?

Best Regards,
Nir
