### ISSUE TITLE
Import resources

### ISSUE THREAD

**Issue by cristian98149** [terraform-redhat/terraform-provider-rhcs#92]
Hi,
there is no way to import manually created resources?

BR

**Comment by OurFriendIrony** [comment]
fyi, I saw a MR get merged that supports import for `rhcs_cluster_rosa_classic`, I expect it'll be in the 1.2.0 release within the next 2 weeks. I've just used a local build of `main` to test this import as it appears to work perfectly
ref: https://github.com/terraform-redhat/terraform-provider-rhcs/pull/183

**Comment by nirarg** [comment]
Hi @cristian98149 and @OurFriendIrony ,
rosa_cluster import was added in v1.2.0

I'm closing this issue, feel free to open new issues for any question/problem

Best Regards,
Nir
