### ISSUE TITLE
Too much time for creating machine pool

### ISSUE THREAD

**Issue by cristian98149** [terraform-redhat/terraform-provider-rhcs#93]
I was trying to create a machine pool but it takes very much time (after 14 min nothing has been created).

Any considerations?

BR

**Comment by nirarg** [comment]
Hi @cristian98149 ,

Thank you for the feedback
I know this ticket was opened more than 2 month ago
There where many changes and improvements in the provider
Is this still relevant?
If yes, please add more info about this issue with the latest provider

Thanks,
Nir
